### ISSUE TITLE
Error al hacer push

### ISSUE THREAD

**Issue by LuisMiguel-Sor** [lbenet/2023-1_TSFC3#22]
Hola, disculpen estaba tratando de hacer push nada más pare tener actualizado mi fork pero al tratar de hacerlo (luego de hacer pull) me sale el error que se muestra en la imagen. Leí un poco y según entendí tiene que ver con que yo tengo una rama que no existe en el repositorio original así que no sé si debería de eliminarla o existe otro método para evitar este error.
![image](https://user-images.githubusercontent.com/62694914/204097830-f24cef50-2a61-461d-b80b-cef318a05e9a.png)

**Comment by Julian-RC** [comment]
Entiendo que hiciste pull del main de Luis... Lo que creo que te hace falta es hacer un pull de tu fork.. me parece que ese es el error. Ya intentaste algo del estilo: `git pull Mirepo` ?

**Comment by LuisMiguel-Sor** [comment]
No, no había hecho ese pull pero al hacerlo me dice que hay un conflicto. Por el lugar que dice que está el conflicto supongo que es lo mismo con lo que tuve problemas cuando estuve haciendo los commit.
![image](https://user-images.githubusercontent.com/62694914/204098604-3465b3fb-4c10-4a5e-aebf-c0748c5935e0.png)

**Comment by lbenet** [comment]
Sugiero resolverlo en clase el lunes, y que mejor avances en la tarea 2... recuerda abrir (desde la rama master actualizada) una nueva rama.

**Comment by lbenet** [comment]
Resuelto en clase
