### ISSUE TITLE
Errores de markdown en `PtoFlotante.jl`

### ISSUE THREAD

**Issue by LuEdRaMo** [lbenet/2023-1_TSFC3#4]
Al generar los notebooks encontré dos pequeños errores en `PtoFlotante.jl`. Por un lado, en la línea 

https://github.com/lbenet/2023-1_TSFC3/blob/4645ea81a90ce0a2727fec099c42f5c86b9b69eb/docs/02-PtoFlotante.jl#L507

me parece que debería ser `abajo` en vez de `arriba`, pues el redondeo hacia arriba se ejemplifica en la celda anterior. Por otro lado, en las líneas

https://github.com/lbenet/2023-1_TSFC3/blob/4645ea81a90ce0a2727fec099c42f5c86b9b69eb/docs/02-PtoFlotante.jl#L437
https://github.com/lbenet/2023-1_TSFC3/blob/4645ea81a90ce0a2727fec099c42f5c86b9b69eb/docs/02-PtoFlotante.jl#L440

hay tres instrucciones `$e_\max$`. Sin embargo, al renderizar el notebook me marcó un error de LaTeX, el cual se puede corregir cambiando las anteriores por `$e_\textrm{max}$`.

**Comment by lbenet** [comment]
Muchas gracias por detectar las erratas y abrir este comentario; hoy por la tarde lo corregiré.

**Comment by lbenet** [comment]
Resuelto en https://github.com/lbenet/2023-1_TSFC3/commit/ef1d7f01a43f7b3ab7cb4ba6f1948be2bbf70b20... ya está en main.
