### ISSUE TITLE
Aclaraciones Tarea 1

### ISSUE THREAD

**Issue by LuEdRaMo** [lbenet/2023-1_TSFC3#8]
1. `Inf` puede ser ínfimo/supremo de un intervalo, pero ¿puede pertenecer a él? Es decir, `Inf ∈ Intervalo(0, Inf)` es `true` o `false`. Una implementación directa de `∈`  nos daría `true`; pero si es `false`, entonces hay que pescar este caso a mano. 

2. Me parece que las dos siguientes líneas son el mismo test:
https://github.com/lbenet/2023-1_TSFC3/blob/d87daf80f03763ee1734cbc63c450931eef09fe2/Intervalos/test/tarea1.jl#L82
https://github.com/lbenet/2023-1_TSFC3/blob/d87daf80f03763ee1734cbc63c450931eef09fe2/Intervalos/test/tarea1.jl#L92
3. Los dos test sugieren que se debe **definir** `∅ * [a] = ∅` y `[0] * [a] = [0]`. Estos se tendrían que definir como un caso particular, ya que no se siguen directamente de la definición de producto entre intervalos que vimos. 
https://github.com/lbenet/2023-1_TSFC3/blob/d87daf80f03763ee1734cbc63c450931eef09fe2/Intervalos/test/tarea1.jl#L91
https://github.com/lbenet/2023-1_TSFC3/blob/d87daf80f03763ee1734cbc63c450931eef09fe2/Intervalos/test/tarea1.jl#L92
4. En el test 
https://github.com/lbenet/2023-1_TSFC3/blob/d87daf80f03763ee1734cbc63c450931eef09fe2/Intervalos/test/tarea1.jl#L101
el intervalo `d` contiene al cero. Entonces, ¿`/` debe ser la divisón normal (en cuyo caso el test no debería pasar porque la divisón normal requiere `0 ∉ d`) o `/` debe llamar a la división extendida cuando sea necesario?

**Comment by lbenet** [comment]
Gracias por las preguntas; trataré de responderlas:

1. Los intervalos que consideramos son "acotados y cerrados". Entonces, `Intervalo(1, Inf)` representa todos los números reales mayores o iguales a 1... pero reales! Entonces, como `Inf` no es un real, `Inf ∈ Intervalo(0, Inf)` debería ser `false`, lo mismo que `Inf ∈ Intervalo(-Inf,Inf)` o que `Inf ∈  intervalo_Vacio()`.
2. Good catch :-)
3. En cuanto a `∅ * [a] == ∅`, dado que `∅` es un intervalo *bien definido*, entonces debe ser posible usarlo en la multiplicación, y el resultado que está en el test es el único razonable. Algo parecido se puede argumentar para `[0] * [a] == [0]`, dado que `[a]` es un intervalo y eso implica que es cerrado y acotado; la sutileza en este caso es que no debes redondear.
4. Contestando la pregunta, `u/d` es la división usual; usaremos la división extendida más adelante. Una vez dicho esto, tienes razón que en la división usual (`/`) uno excluye del denominador intervalos que incluyen al cero. Por otro lado, también puedes pensar que el resultado de ese test, `Intervalo(-Inf,Inf)` es *trivial* en el sentido de que la recta real, y de hecho es el *hull* de los dos intervalos disjuntos. Ciertamente, este intervalo es *demasiado ancho*, pero incluye a todos los valores posibles de la división de un elemento en `u` entre uno en `d`, excepto si el elemento del denominador es el cero. Con esta extensión a intervalos que incluyen el cero, la división sigue cumpliendo la "monotonicidad de inclusión".

Motivado por los dos primeros puntos, ajustaré un poco los tests...

**Comment by lbenet** [comment]
Otra cosa: Respecto a `3.`, vale quizás la pena notar que `0 * a` e `Intervalo(0.0) * a` dan resultados distintos (por el redondeo!).

**Comment by Julian-RC** [comment]
Cierro Issue ya que hace un mes se agregaron los cambios. Saludos!
